name: vlc-ios
on:
  push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
        
    
